server:
  disable: true

clients:
- url: "http://loki:3100/loki/api/v1/push"
  # basic_auth:
  #   username: "admin"
  #   password: "admin"

positions:
  filename: /tmp/positions/positions.yaml

target_config:
  sync_period: 10s

scrape_configs:
- job_name: traefik-logs
  static_configs:
  - targets:
    - localhost
    labels:
      job: access-logs
      host: traefik
      __path__: /var/log/*.json